export const CHANGE_TOP_BANNERS = 'recommend/CHANGE_TOP_BANNERS'
export const CHANGE_HOT = 'recommend/CHANGE_HOT'
export const CHANGE_NEW = 'recommend/CHANGE_NEW'
export const CHANGE_UPRANKING = 'recommend/CHANGE_UPRANKING'
export const CHANGE_NEWRANKING = 'recommend/CHANGE_NEWRANKING'
export const CHANGE_ORIRANKING = 'recommend/CHANGE_ORIRANKING'